package com.group130.laundryapp.DAL.Configuration.Google.GoogleOAuth;

import com.group130.laundryapp.DAL.Configuration.Auth.JwtConfig;
import com.group130.laundryapp.Domain.Entity.*;
import com.group130.laundryapp.Domain.Enum.AccountRole;
import com.group130.laundryapp.DAL.Repository.*;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.Authentication;
import org.springframework.security.oauth2.core.oidc.user.OidcUser;
import org.springframework.security.web.authentication.AuthenticationSuccessHandler;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.util.UriComponentsBuilder;

import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Optional;

@Component
@RequiredArgsConstructor
@Slf4j
public class GoogleOAuthSuccessHandler implements AuthenticationSuccessHandler {

    private final AccountRepository      accountRepository;
    private final UserRepository         userRepository;
    private final RefreshTokenRepository refreshTokenRepository;
    private final JwtConfig              jwtConfig;

    @Value("${google.frontend-redirect-url}")
    private String frontendRedirectUrl;

    @Override
    @Transactional
    public void onAuthenticationSuccess(
            HttpServletRequest  request,
            HttpServletResponse response,
            Authentication      authentication
    ) throws IOException {

        // Spring has already verified everything with Google by the time
        // this method runs. We just read the confirmed user profile.
        OidcUser oidcUser = (OidcUser) authentication.getPrincipal();

        String  email      = oidcUser.getEmail();
        String  firstName  = oidcUser.getGivenName();
        String  lastName   = oidcUser.getFamilyName();
        String  pictureUrl = oidcUser.getPicture();
        String  googleId   = oidcUser.getSubject();
        boolean verified   = Boolean.TRUE.equals(oidcUser.getEmailVerified());

        if (!verified) {
            response.sendRedirect(frontendRedirectUrl + "/auth/error?reason=email_not_verified");
            return;
        }

        // ── Register or login ─────────────────────────────────────────
        Optional<Account> existing = accountRepository.findByEmail(email);
        Account account;

        if (existing.isPresent()) {
            account = existing.get();
            account.setEmailVerified(true);
            account.setLastLoginAt(OffsetDateTime.now());

            userRepository.findByAccountId(account.getId()).ifPresent(user -> {
                if (user.getAvatarUrl() == null && pictureUrl != null) {
                    user.setAvatarUrl(pictureUrl);
                    userRepository.save(user);
                }
            });

            accountRepository.save(account);
            log.info("Google OAuth: existing user logged in [{}]", email);

        } else {
            account = Account.builder()
                    .email(email)
                    .phone(null)
                    .passwordHash("")
                    .role(AccountRole.USER)
                    .isEmailVerified(true)
                    .googleId(googleId)
                    .lastLoginAt(OffsetDateTime.now())
                    .build();
            accountRepository.save(account);

            User user = User.builder()
                    .account(account)
                    .firstName(firstName != null ? firstName : "")
                    .lastName(lastName   != null ? lastName  : "")
                    .avatarUrl(pictureUrl)
                    .build();
            userRepository.save(user);

            log.info("Google OAuth: new user registered [{}]", email);
        }

        // ── Generate JWT pair ─────────────────────────────────────────
        String accessToken  = jwtConfig.generateAccessToken(account);
        String refreshToken = jwtConfig.generateRefreshToken(account);

        /*
         * FIX — RefreshToken builder field names.
         *
         * Your uploaded code used .RefreshTokenHash() and .AccessTokenHash()
         * (capital R and A). Java builder methods generated by Lombok follow
         * the field name exactly. Check your RefreshToken entity and match
         * the field names here.
         *
         * If your entity has:
         *   private String tokenHash;          → use .tokenHash(...)
         *   private String accessTokenHash;    → use .accessTokenHash(...)
         *
         * Adjust the two lines below to match your actual entity field names.
         */
        RefreshToken rt = RefreshToken.builder()
                .account(account)
                .RefreshTokenHash(hashToken(refreshToken))// ← match your entity field name
                .AccessTokenHash(hashToken(accessToken))  // ← match your entity field name
                .expiresAt(OffsetDateTime.now().plusDays(7))
                .build();
        refreshTokenRepository.save(rt);

        // ── Kill the OAuth2 session — we no longer need it ────────────
        HttpSession session = request.getSession(false);
        if (session != null) session.invalidate();

        // ── Redirect browser to frontend with tokens in query params ──
        String redirectUrl = UriComponentsBuilder
                .fromUriString(frontendRedirectUrl + "/auth/callback")
                .queryParam("access_token",  accessToken)
                .queryParam("refresh_token", refreshToken)
                .queryParam("role",          account.getRole().name())
                .build()
                .toUriString();

        response.sendRedirect(redirectUrl);
    }

    private String hashToken(String token) {
        try {
            var digest = java.security.MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(
                    token.getBytes(java.nio.charset.StandardCharsets.UTF_8));
            var sb = new StringBuilder();
            for (byte b : hash) sb.append(String.format("%02x", b));
            return sb.toString();
        } catch (Exception e) {
            throw new RuntimeException("Token hash failed", e);
        }
    }
}