package com.group130.laundryapp.Domain.Entity;

import com.group130.laundryapp.Domain.Enum.OrderStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Entity
@Table(name = "orders",
        indexes = {
                @Index(name = "idx_orders_user_id",     columnList = "user_id"),
                @Index(name = "idx_orders_business_id", columnList = "business_id"),
                @Index(name = "idx_orders_rider_id",    columnList = "rider_id"),
                @Index(name = "idx_orders_status",      columnList = "status"),
        })
@Getter @Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Order {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * Human-readable order number — generated by DB trigger (ORD-YYYYMMDD-XXXX).
     * Never set this in application code; leave null on INSERT.
     */
    @Column(name = "order_number", nullable = false, unique = true, length = 20, updatable = false)
    private String orderNumber;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_orders_user_id"))
    private User user;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "business_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_orders_business_id"))
    private Business business;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rider_id",
            foreignKey = @ForeignKey(name = "fk_orders_rider_id"))
    private Rider rider;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 25)
    @Builder.Default
    public OrderStatus status = OrderStatus.PENDING;

    // Pickup
    @Column(name = "pickup_address", nullable = false, columnDefinition = "TEXT")
    private String pickupAddress;
    @Column(name = "pickup_lat")  private Double pickupLat;
    @Column(name = "pickup_lng")  private Double pickupLng;
    @Column(name = "pickup_time") private OffsetDateTime pickupTime;

    // Delivery
    @Column(name = "delivery_address", nullable = false, columnDefinition = "TEXT")
    private String deliveryAddress;
    @Column(name = "delivery_lat")  private Double deliveryLat;
    @Column(name = "delivery_lng")  private Double deliveryLng;
    @Column(name = "delivery_time") private OffsetDateTime deliveryTime;

    // Financials
    @Column(nullable = false, precision = 12, scale = 2) @Builder.Default
    private BigDecimal subtotal       = BigDecimal.ZERO;

    @Column(name = "delivery_fee", nullable = false, precision = 12, scale = 2) @Builder.Default
    private BigDecimal deliveryFee    = BigDecimal.ZERO;

    @Column(name = "discount_amount", nullable = false, precision = 12, scale = 2) @Builder.Default
    private BigDecimal discountAmount = BigDecimal.ZERO;

    @Column(name = "total_amount", nullable = false, precision = 12, scale = 2) @Builder.Default
    private BigDecimal totalAmount    = BigDecimal.ZERO;

    @Column(columnDefinition = "TEXT")  private String notes;
    @Column(name = "cancelled_reason", columnDefinition = "TEXT") private String cancelledReason;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @Builder.Default
    private List<OrderItem> items = new ArrayList<>();

    @OneToOne(mappedBy = "order", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private Payment payment;

    @OneToOne(mappedBy = "order", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private Review review;

    // Helper
    public void addItem(OrderItem item) {
        items.add(item);
        item.setOrder(this);
    }

    public void recalculateTotals() {
        this.subtotal = items.stream()
                .map(OrderItem::getLineTotal)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        this.totalAmount = subtotal.add(deliveryFee).subtract(discountAmount);
    }


}


